name: CI

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Specify your desired Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

  notify:
    runs-on: ubuntu-latest
    needs: test 

    steps:
      - name: Send Slack Notification
        if: success()  
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PR_LINK: ${{ github.event.pull_request.html_url }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"<@${{ secrets.SLACK_MEMBER_ID }}> has opened a new pull request: <${PR_LINK}|${{ github.event.pull_request.title }}>. Please review!\"}" $SLACK_WEBHOOK
